name: classroom_app
description: Öğrenciler ve öğretmenler için eğitim platformu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.6.0
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true 